In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df_4 = pd.read_csv("https://raw.githubusercontent.com/su-mt4007/data/refs/heads/main/cell_phones_total.csv").copy()

# Function to convert string values to numeric
def convert_to_numeric(value):
    if isinstance(value, str):
        multipliers = {'k': 1e3, 'M': 1e6, 'B': 1e9}
        try:
            # Extract numeric part and suffix
            num_part = float(value[:-1])  # All but the last character
            suffix = value[-1]  # Last character
            return num_part * multipliers.get(suffix, 1)  # Multiply by corresponding multiplier
        except ValueError:
            return np.nan  # Handle invalid entries
    return value  # If not a string, return as-is

df_4.iloc[:, 1:] = df_4.iloc[:, 1:].map(convert_to_numeric) #convert to normal numbers

object_cols = df_4.iloc[:, 1:].select_dtypes(include=['object']).columns #singel out the problematic columns

df_4[object_cols] = df_4[object_cols].apply(pd.to_numeric, errors='coerce') #convert the type

df_4.iloc[:, 1:] = df_4.iloc[:, 1:].ffill(axis=1) #"forward-filling" the missing values

df_cell = df_4.sort_values(by='2015', ascending=False) 

df_cell

iso-3  1960  1965  1966  1967  1968  1969  1970  1971  1972  ...  \
35    CHN   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
87    IND   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
200   USA   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
86    IDN   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
26    BRA   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
130   MNP   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
123   MHL   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
144   NRU   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
195   TUV   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
8     ASM   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

            2010         2011          2012          2013          2014  \
35   859000000.0  986000000.0  1.110000e+09  1.230000e+09  1.290000e+09   
87   752000000.0  894000000.0  8.650000e+08  8.860000e+08  9.440000e+08   
200  285000000.0  297000000.0  3.050000e+08  3.110000e+08  3.560000e+08   
86   211000000.0  250000000.0  2.820000e+08  3.130000e+08  3.260000e+08   
26   197000000.0  234000000.0  2.480000e+08  2.710000e+08  2.810000e+08   
..           ...          ...           ...           ...           ...   
130      20500.0      20500.0  2.050000e+04  2.050000e+04  2.050000e+04   
123         66.0         66.0  6.600000e+01  6.600000e+01  1.550000e+04   
144        620.0        670.0  6.800000e+02  6.800000e+02  6.800000e+02   
195        160.0        213.0  2.800000e+02  3.400000e+02  3.800000e+02   
8          225.0        225.0  2.250000e+02  2.250000e+02  2.250000e+02   

             2015          2016          2017          2018          2019  
35   1.290000e+09  1.360000e+09  1.470000e+09  1.650000e+09  1.730000e+09  
87   1.000000e+09  1.130000e+09  1.170000e+09  1.180000e+09  1.150000e+09  
200  3.820000e+08  3.960000e+08  4.000000e+08  4.220000e+08  4.220000e+08  
86   3.390000e+08  3.860000e+08  4.350000e+08  3.190000e+08  3.450000e+08  
26   2.580000e+08  2.440000e+08  2.180000e+08  2.070000e+08  2.070000e+08  
..            ...           ...           ...           ...           ...  
130  2.050000e+04  2.050000e+04  2.050000e+04  2.050000e+04  2.050000e+04  
123  1.550000e+04  1.550000e+04  1.600000e+04  1.600000e+04  1.600000e+04  
144  9.400000e+02  9.900000e+02  1.000000e+04  1.000000e+04  1.000000e+04  
195  6.600000e+02  7.600000e+02  8.000000e+02  8.000000e+02  8.000000e+02  
8    2.250000e+02  2.250000e+02  2.250000e+02  2.250000e+02  2.250000e+02  

[214 rows x 57 columns]

## Joining data

We have the cleaned cell phone data from previous homework above. We will start by cleaning the population data set.



In [23]:
df = pd.read_csv("https://raw.githubusercontent.com/su-mt4007/data/refs/heads/main/pop_data.csv")

nan_locations = df.isna()
nan_indices = nan_locations.stack()[nan_locations.stack()]

nan_indices 


110  1960    True
     1961    True
     1962    True
     1963    True
     1964    True
             ... 
196  1985    True
     1986    True
     1987    True
     1988    True
     1989    True
Length: 91, dtype: bool

We take a closer look at row 110 and 196 and take the appropriate measure.


In [24]:
print(df.loc[110], df.loc[196])

Unnamed: 0    110
iso-3         INX
1960          NaN
1961          NaN
1962          NaN
             ... 
2016          NaN
2017          NaN
2018          NaN
2019          NaN
2020          NaN
Name: 110, Length: 63, dtype: object Unnamed: 0          196
iso-3               PSE
1960                NaN
1961                NaN
1962                NaN
                ...    
2016          4367088.0
2017          4454805.0
2018          4569087.0
2019          4685306.0
2020          4803269.0
Name: 196, Length: 63, dtype: object


Will delete 110 cause no data but keep the 196.

In [27]:
df_pop = df.drop(index=110)
df_pop

Unnamed: 0 iso-3         1960         1961         1962         1963  \
0             0   ABW      54608.0      55811.0      56682.0      57475.0   
1             1   AFE  130692579.0  134169237.0  137835590.0  141630546.0   
2             2   AFG    8622466.0    8790140.0    8969047.0    9157465.0   
3             3   AFW   97256290.0   99314028.0  101445032.0  103667517.0   
4             4   AGO    5357195.0    5441333.0    5521400.0    5599827.0   
..          ...   ...          ...          ...          ...          ...   
261         261   XKX     947000.0     966000.0     994000.0    1022000.0   
262         262   YEM    5542459.0    5646668.0    5753386.0    5860197.0   
263         263   ZAF   16520441.0   16989464.0   17503133.0   18042215.0   
264         264   ZMB    3119430.0    3219451.0    3323427.0    3431381.0   
265         265   ZWE    3806310.0    3925952.0    4049778.0    4177931.0   

            1964         1965         1966         1967  ...         2011  \
0        58178.0      58782.0      59291.0      59522.0  ...     101288.0   
1    145605995.0  149742351.0  153955516.0  158313235.0  ...  537792950.0   
2      9355514.0    9565147.0    9783147.0   10010030.0  ...   29249157.0   
3    105959979.0  108336203.0  110798486.0  113319950.0  ...  366489204.0   
4      5673199.0    5736582.0    5787044.0    5827503.0  ...   24259111.0   
..           ...          ...          ...          ...  ...          ...   
261    1050000.0    1078000.0    1106000.0    1135000.0  ...    1791000.0   
262    5973803.0    6097298.0    6228430.0    6368014.0  ...   25475610.0   
263   18603097.0   19187194.0   19789771.0   20410677.0  ...   52443325.0   
264    3542764.0    3658024.0    3777680.0    3901288.0  ...   14265814.0   
265    4310332.0    4447149.0    4588529.0    4734694.0  ...   13025785.0   

            2012         2013         2014         2015         2016  \
0       102112.0     102880.0     103594.0     104257.0     104874.0   
1    552530654.0  567892149.0  583651101.0  600008424.0  616377605.0   
2     30466479.0   31541209.0   32716210.0   33753499.0   34636207.0   
3    376797999.0  387204553.0  397855507.0  408690375.0  419778384.0   
4     25188292.0   26147002.0   27128337.0   28127721.0   29154746.0   
..           ...          ...          ...          ...          ...   
261    1807106.0    1818117.0    1812771.0    1788196.0    1777557.0   
262   26223391.0   26984002.0   27753304.0   28516545.0   29274002.0   
263   53145033.0   53873616.0   54729551.0   55876504.0   56422274.0   
264   14744658.0   15234976.0   15737793.0   16248230.0   16767761.0   
265   13265331.0   13555422.0   13855753.0   14154937.0   14452704.0   

            2017         2018         2019         2020  
0       105439.0     105962.0     106442.0     106585.0  
1    632746570.0  649757148.0  667242986.0  685112979.0  
2     35643418.0   36686784.0   37769499.0   38972230.0  
3    431138704.0  442646825.0  454306063.0  466189102.0  
4     30208628.0   31273533.0   32353588.0   33428486.0  
..           ...          ...          ...          ...  
261    1791003.0    1797085.0    1788878.0    1790133.0  
262   30034389.0   30790513.0   31546691.0   32284046.0  
263   56641209.0   57339635.0   58087055.0   58801927.0  
264   17298054.0   17835893.0   18380477.0   18927715.0  
265   14751101.0   15052184.0   15354608.0   15669666.0  

[265 rows x 63 columns]

Now lets combine the cell phone data and the population data.

In [30]:
df_cell_melt = pd.melt(df_cell, id_vars=["iso-3"], var_name="Year", value_name="Cell")

df_pop_melt = pd.melt(df_pop, id_vars=["iso-3"], var_name="Year", value_name="Pop")
df_pop_melt

iso-3        Year         Pop
0       ABW  Unnamed: 0         0.0
1       AFE  Unnamed: 0         1.0
2       AFG  Unnamed: 0         2.0
3       AFW  Unnamed: 0         3.0
4       AGO  Unnamed: 0         4.0
...     ...         ...         ...
16425   XKX        2020   1790133.0
16426   YEM        2020  32284046.0
16427   ZAF        2020  58801927.0
16428   ZMB        2020  18927715.0
16429   ZWE        2020  15669666.0

[16430 rows x 3 columns]